### ISSUE TITLE
Rotate <XAxis /> tick lables

### ISSUE THREAD

**Issue by VincentRichard555** [williaster/data-ui#109]
Hi, this is a pretty simple issue but I can't seem to figure out how to rotate x axis tick labels.

What I am trying to do is essentially add

` .attr("transform", "rotate(-90)")`

to the text element of the x axis label.

I see there is `tickLabelComponent` prop of `<XAxis />` but I cannot seem to get it to work.

Thanks

**Comment by williaster** [comment]
Hey @VincentRichard555, thanks for checking out `data-ui`. In theory this should work by setting the `tickLabelProps` to something like `(d, i) => ({ transform: 'rotate(45)' })`, but it doesn't work because of the way transforms are done in the version of `@vx/axis` I'm using. 

I'm planning to bump all `@vx` packages this week and after that this will be possible by setting `tickLabelProps={(d, i) => ({ angle: 45 })}`. `angle` (and anything else returned in this object) is used as a prop passed to a `@vx/text` `<Text />` component, which is the default tick label component in `@vx/axis`. I'll also plan to expose the `tickComponent` prop when I make this change and tag you in the PR 👍

**Comment by VincentRichard555** [comment]
Thanks that sounds great!

**Comment by williaster** [comment]
@VincentRichard555 this should now be fixed/exposed in `@data-ui/xy-chart` [`v0.0.59`](https://github.com/williaster/data-ui/blob/master/CHANGELOG.md#v0058). 

I also added a [storybook demo](https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=TickLabelPlayground&full=0&down=0&left=1&panelRight=0) so you can play with the various props 🚀 and here's an [example codesandbox](https://codesandbox.io/s/k10jo1rnyr).

![tick-label-playground](https://user-images.githubusercontent.com/4496521/42070010-75811e54-7b09-11e8-9a1e-1fb693007b7a.gif)

**Comment by VincentRichard555** [comment]
Thanks! This solves my problem. I appreciate your fast response to my issue.

**Comment by AdeBode** [comment]
@williaster, have these changes for Xaxis and Yaxis tick labels been implemented for the Histogram package?

**Comment by williaster** [comment]
hey @AdeBode this has **not** been ported to `@data-ui/histogram` yet, it shouldn't be too difficult, though. 

I opened #135 to track that feature. I'm pretty swamped at the moment so would totally welcome PRs, or I can probably find some time in the next ~4 weeks to get it done.

**Comment by AdeBode** [comment]
@williaster Thanks for the quick response! Also swamped at the moment so I wont be able to make a PR (maybe in the future!). Anyhow, I just want to say thanks for the collection, I am really enjoying it!

**Comment by caglarbayatli** [comment]
@williaster I think Xaxis label angle still does not work properly and  its "tickLabelComponent" prop is not using?
Thanks
